#!/bin/bash
echo ""
echo "check is start......"
flag=0;
process=`ps aux |grep -v "grep"|grep "bash -i"`
if [ -n "$process" ];then
	echo ".........suspicious process, process name..........."
	flag=1;
	echo "$process"
fi;
if [ -f "/tmp/1" -o -f "/tmp/tshd" ] ;then 
	echo ".......exist vicious file.............."
	flag=1;
fi;

tshd=`find / -name "tshd*"`
if [ -n "$tshd" ];then
	echo "..........tshd file exist....."
	echo $tshd
	flag=1
fi;

if [ "$flag" -eq 0 ];then
	process2=`ps aux |grep -v "grep" |grep "openssl s_client -quiet -connect"`
	if [ -n "$process2" ];then
		echo ".......exist vicious process......."
		echo $process2
	fi;
fi;



if [ "$flag" -eq 0 ];then
	echo "111.111.111.111  terminal.flach.cn" >> /etc/hosts
	echo "111.111.111.111  update.flach.cn"  >> /etc/hosts
	sleep 5s
	connection=`netstat -anutp |grep -v "grep"|grep "111.111.111.111"`
	if [ -n "$connection" ]; then 
		echo ".......exist vicious connection ...... "
		echo $connection
		flag=1
	fi;
	sed -i '/^111.111.111.111/d' /etc/hosts
	
fi;

echo "chek is end ........"
if [ "$flag" -eq 1 ] ;then
	echo "this is infect !!!!!!!!!!!!!!!  "
else
	echo "this is uninfected!"
fi;
